version: '3.6'



services:
    #Urban API
    # urban-api:
    #     container_name: urban
    #     build: ./
    #     command: npm start
    #     working_dir: /usr/src/urban-api
    #     environment: 
    #         POSTGRES_USER: michy
    #         REDIS_URL: redis://redis://6379
    #     links:
    #         - postgres
    #         - redis
    #     ports:
    #     - "3000:3000"
    #     volumes:
    #     - ./:/usr/src/urban-api

    # Postgres
    postgres:
        image: postgres
        environment:
          POSTGRES_USER: michy
          POSTGRES_PASSWORD: password
          POSTGRES_DB: urban
        ports:
          - '5432:5432'
        # volumes:
        #   # - ${PWD}/latest.dump:/latest.dump
        #   - pgdata:/var/lib/postgresql/data
    
    redis:
        image: redis
        ports:
          - '6379:6379'
    
    # volumes: 
    #   pgdata:

    